#server:
#  port: 8080
#  servlet:
#    context-path: /api
#
#spring:
#  datasource:
#    url: "jdbc:mysql://localhost:3306/book"
#    username: root
#    password: 123456
#  jpa:
#    hibernate:
#      ddl-auto: update  # Tự động tạo và cập nhật database schema (chọn 'none' nếu không muốn tự động tạo schema)
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#
#logging:
#  level:
#    org.springframework: DEBUG
#    com.example: DEBUG
#
#jwt:
#  signerKey: "BaF0iztmWY0sER0dO0IWZczUEYDeADDxhD+CPzewPFnesrqV/3sXxXlmrix0AjTG"
#  expiration: 3600000

server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      max-file-size: 100MB  # Đặt kích thước tối đa cho mỗi file (ví dụ 100MB)
      max-request-size: 100MB  # Đặt kích thước tối đa cho tổng thể yêu cầu upload

jwt:
  signerKey: "BaF0iztmWY0sER0dO0IWZczUEYDeADDxhD+CPzewPFnesrqV/3sXxXlmrix0AjTG"
  expiration: 360000000


  mail:
    host: smtp.gmail.com
    port: 587
    username: thanhdao672002@gmail.com
    password: xjog xldx smay krwi
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org.springframework: DEBUG
    com.yourpackage: DEBUG


minio:
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minio123
  bucket: user-avatar
  video-bucket : user-video
