#server:
#  port: 8080
#  servlet:
#    context-path: /api
#
#spring:
#  datasource:
#    url: "jdbc:mysql://localhost:3306/book"
#    username: root
#    password: 123456
#  jpa:
#    hibernate:
#      ddl-auto: update  # Tự động tạo và cập nhật database schema (chọn 'none' nếu không muốn tự động tạo schema)
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#
#logging:
#  level:
#    org.springframework: DEBUG
#    com.example: DEBUG
#
#jwt:
#  signerKey: "BaF0iztmWY0sER0dO0IWZczUEYDeADDxhD+CPzewPFnesrqV/3sXxXlmrix0AjTG"
#  expiration: 3600000

server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

jwt:
  signerKey: "BaF0iztmWY0sER0dO0IWZczUEYDeADDxhD+CPzewPFnesrqV/3sXxXlmrix0AjTG"
  expiration: 360000000


minio:
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minio123
  bucket: user-avatar
