version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-book-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: book
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - book-net

  springboot-app:
    build: .
    container_name: springboot-book-api
    depends_on:
      - mysql
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/book
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
    networks:
      - book-net

volumes:
  mysql_data:

networks:
  book-net:
